var config_byValues_en = {
	"species_record_tooltip": "Click on a cell to view more details about the record",
	"islands_record_tooltip": "Click on a cell to pan to that island on the map",
	"tib_record_tooltip": "Any threatened species on an island from the Threatened Island Biodiversity Database (TIB).",
	"no_filter": "No search filters chosen.  Please select items from the Search pane to filter by ...",
	"Error selecting the item in the data table": "Error selecting the item in the data table",
	"Download": "Download",
	"Export": "Export",
	"Export Map": "Export Map",
	"Export to CSV": "Export to CSV",	
	"Exporting Map": "Exporting Map",
	"Exporting to CSV": "Exporting to CSV",
	"Download Map": "Download Map",
	"Download CSV": "Download CSV",
	"Processing": "Processing",
	"No thumbnail images found": "No thumbnail images found",
	"Filter": "Filter",
	"Species Details": "Species Details",
	"Location Details": "Location Details",
	"Eradication Details": "Eradication Details",
	"Contact Details": "Contact Details",
	"Common Name": "Common Name",
	"Scientific Name": "Scientific Name",
	"Type (Animal)": "Type (Animal)",
	"Year of Introduction": "Year of Introduction",
	"Latitude": "Latitude",
	"Longitude": "Longitude",
	"Status (Eradication)": "Status (Eradication)",
	"Eradication Status": "Status (Eradication)",
	"Island Eradication Type" : "Island Eradication Type",
	"Primary Eradication Method": "Primary Eradication Method",
	"Secondary Eradication Method": "Secondary Eradication Method",
	"Tertiary Eradication Method": "Tertiary Eradication Method",
	"Eradication Start Date": "Eradication Start Date",
	"Eradication End Date": "Eradication End Date",	
	"Primary Baiting Method": "Primary Baiting Method",
	"Secondary Baiting Method": "Secondary Baiting Method",
	"Eradication Method Details": "Eradication Method Details",
	"Trapping Method Details": "Trapping Method Details",
	"Method Description": "Method Description",
	"Primary Toxicant": "Primary Toxicant",
	"Secondary Toxicant": "Secondary Toxicant",
	"Cost": "Cost",
	"Eradication Contact": "Eradication Contact",
	"Contact Email": "Contact Email",
	"Contact Organization": "Contact Organization",
	"Organization Website": "Organization Website",
	"Island Code": "Island Code",
	"Island Name": "Island Name",
	"Name": "Name",
	"Coordinates": "Coordinates",
	"Region": "Region",
	"Country": "Country",
	"Archipelago": "Archipelago",
	"Area (sq km)": "Area (sq km)",	
	"Human Population": "Human Population",
	"Invasive Species": "Invasive Species",
	"Threatened Species": "Threatened Species",
	"Threatened": "Threatened",
	"eradication": "eradication",
	"eradications": "eradications",
	"Eradications": "Eradications",
	"online": "online",
	"search in the TIB": "search in the TIB",
	"None": "None",
	"none": "none",
	"yes": "yes",
	"no": "no",	
	"Populations": "Populations",
	"populations": "populations",
	"population": "population",
	"no common name": "no common name",
	"unknown": "unknown",
	"Status": "Status",
	"Year": "Year",
	"chart: x-axis": "Year",
	"chart: y-axis": "Number of Successful Eradications",
	" -- all -- ": " -- all -- ",
	"Arctic Ocean - North Canada": "Arctic Ocean - North Canada",
	"Atlantic Ocean - North": "Atlantic Ocean - North",
	"Atlantic Ocean - South": "Atlantic Ocean - South",
	"Baltic sea": "Baltic sea",
	"Caribbean": "Caribbean",
	"Indian Ocean - East": "Indian Ocean - East",
	"Indian Ocean - West": "Indian Ocean - West",
	"Mediterranean": "Mediterranean",
	"Nusantarian Sea": "Nusantarian Sea",
	"Pacific Ocean - North East": "Pacific Ocean - North East",
	"Pacific Ocean - North West": "Pacific Ocean - North West",
	"Pacific Ocean - South East": "Pacific Ocean - South East",
	"Pacific Ocean - South West": "Pacific Ocean - South West",
	"Åland Islands": "Åland Islands",
	"Albania": "Albania",
	"Algeria": "Algeria",
	"American Samoa": "American Samoa",
	"Angola": "Angola",
	"Anguilla": "Anguilla",
	"Antarctica": "Antarctica",
	"Antigua and Barbuda": "Antigua and Barbuda",
	"Argentina": "Argentina",
	"Aruba": "Aruba",
	"Australia": "Australia",
	"Bahamas": "Bahamas",
	"Bahrain": "Bahrain",
	"Bangladesh": "Bangladesh",
	"Barbados": "Barbados",
	"Belgium": "Belgium",
	"Belize": "Belize",
	"Benin": "Benin",
	"Bermuda": "Bermuda",
	"Bosnia and Herzegovina": "Bosnia and Herzegovina",
	"Bouvet Island": "Bouvet Island",
	"Brazil": "Brazil",
	"British Indian Ocean Territory": "British Indian Ocean Territory",
	"Brunei Darussalam": "Brunei Darussalam",
	"Bulgaria": "Bulgaria",
	"Cambodia": "Cambodia",
	"Cameroon": "Cameroon",
	"Canada": "Canada",
	"Cape Verde": "Cape Verde",
	"Cayman Islands": "Cayman Islands",
	"Chile": "Chile",
	"China": "China",
	"Christmas Island": "Christmas Island",
	"Cocos (Keeling) Islands": "Cocos (Keeling) Islands",
	"Colombia": "Colombia",
	"Comoros": "Comoros",
	"Congo": "Congo",
	"Congo, The Democratic Republic of the": "Congo, The Democratic Republic of the",
	"Cook Islands": "Cook Islands",
	"Costa Rica": "Costa Rica",
	"Côte D'Ivoire": "Côte D'Ivoire",
	"Croatia": "Croatia",
	"Cuba": "Cuba",
	"Cyprus": "Cyprus",
	"Denmark": "Denmark",
	"Djibouti": "Djibouti",
	"Dominica": "Dominica",
	"Dominican Republic": "Dominican Republic",
	"Ecuador": "Ecuador",
	"Egypt": "Egypt",
	"El Salvador": "El Salvador",
	"Equatorial Guinea": "Equatorial Guinea",
	"Eritrea": "Eritrea",
	"Estonia": "Estonia",
	"Falkland Islands (Malvinas)": "Falkland Islands (Malvinas)",
	"Faroe Islands": "Faroe Islands",
	"Fiji": "Fiji",
	"Finland": "Finland",
	"France": "France",
	"French Guiana": "French Guiana",
	"French Polynesia": "French Polynesia",
	"French Southern Territories": "French Southern Territories",
	"Gabon": "Gabon",
	"Gambia": "Gambia",
	"Georgia": "Georgia",
	"Germany": "Germany",
	"Ghana": "Ghana",
	"Gibraltar": "Gibraltar",
	"Greece": "Greece",
	"Greenland": "Greenland",
	"Grenada": "Grenada",
	"Guadeloupe": "Guadeloupe",
	"Guam": "Guam",
	"Guatemala": "Guatemala",
	"Guernsey": "Guernsey",
	"Guinea": "Guinea",
	"Guinea-Bissau": "Guinea-Bissau",
	"Guyana": "Guyana",
	"Haiti": "Haiti",
	"Heard Island and Mcdonald Islands": "Heard Island and Mcdonald Islands",
	"Honduras": "Honduras",
	"Hong Kong": "Hong Kong",
	"Iceland": "Iceland",
	"India": "India",
	"Indonesia": "Indonesia",
	"Iran, Islamic Republic of": "Iran, Islamic Republic of",
	"Iraq": "Iraq",
	"Ireland": "Ireland",
	"Isle of Man": "Isle of Man",
	"Israel": "Israel",
	"Italy": "Italy",
	"Jamaica": "Jamaica",
	"Japan": "Japan",
	"Jersey": "Jersey",
	"Kenya": "Kenya",
	"Kiribati": "Kiribati",
	"Korea, Democratic People'S Republic of": "Korea, Democratic People'S Republic of",
	"Korea, Republic of": "Korea, Republic of",
	"Kuwait": "Kuwait",
	"Latvia": "Latvia",
	"Lebanon": "Lebanon",
	"Liberia": "Liberia",
	"Libyan Arab Jamahiriya": "Libyan Arab Jamahiriya",
	"Lithuania": "Lithuania",
	"Macao": "Macao",
	"Madagascar": "Madagascar",
	"Malaysia": "Malaysia",
	"Maldives": "Maldives",
	"Malta": "Malta",
	"Marshall Islands": "Marshall Islands",
	"Martinique": "Martinique",
	"Mauritania": "Mauritania",
	"Mauritius": "Mauritius",
	"Mayotte": "Mayotte",
	"Mexico": "Mexico",
	"Micronesia, Federated States of": "Micronesia, Federated States of",
	"Moldova, Republic of": "Moldova, Republic of",
	"Monaco": "Monaco",
	"Montenegro": "Montenegro",
	"Montserrat": "Montserrat",
	"Morocco": "Morocco",
	"Mozambique": "Mozambique",
	"Myanmar": "Myanmar",
	"Namibia": "Namibia",
	"Nauru": "Nauru",
	"Netherlands": "Netherlands",
	"Netherlands Antilles": "Netherlands Antilles",
	"New Caledonia": "New Caledonia",
	"New Zealand": "New Zealand",
	"Nicaragua": "Nicaragua",
	"Nigeria": "Nigeria",
	"Niue": "Niue",
	"Norfolk Island": "Norfolk Island",
	"Northern Mariana Islands": "Northern Mariana Islands",
	"Norway": "Norway",
	"Oman": "Oman",
	"Pakistan": "Pakistan",
	"Palau": "Palau",
	"Palestinian Territory, Occupied": "Palestinian Territory, Occupied",
	"Panama": "Panama",
	"Papua New Guinea": "Papua New Guinea",
	"Peru": "Peru",
	"Philippines": "Philippines",
	"Pitcairn": "Pitcairn",
	"Poland": "Poland",
	"Portugal": "Portugal",
	"Puerto Rico": "Puerto Rico",
	"Qatar": "Qatar",
	"Reunion": "Reunion",
	"Romania": "Romania",
	"Russian Federation": "Russian Federation",
	"Saint Barthélemy": "Saint Barthélemy",
	"Saint Helena": "Saint Helena",
	"Saint Kitts And Nevis": "Saint Kitts And Nevis",
	"Saint Lucia": "Saint Lucia",
	"Saint Martin": "Saint Martin",
	"Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
	"Samoa": "Samoa",
	"Sao Tome and Principe": "Sao Tome and Principe",
	"Saudi Arabia": "Saudi Arabia",
	"Senegal": "Senegal",
	"Seychelles": "Seychelles",
	"Sierra Leone": "Sierra Leone",
	"Singapore": "Singapore",
	"Slovenia": "Slovenia",
	"Solomon Islands": "Solomon Islands",
	"Somalia": "Somalia",
	"South Africa": "South Africa",
	"South Georgia and the South Sandwich Islands": "South Georgia and the South Sandwich Islands",
	"Spain": "Spain",
	"Sri Lanka": "Sri Lanka",
	"Sudan": "Sudan",
	"Suriname": "Suriname",
	"Svalbard and Jan Mayen": "Svalbard and Jan Mayen",
	"Sweden": "Sweden",
	"Syrian Arab Republic": "Syrian Arab Republic",
	"Taiwan, Province of China": "Taiwan, Province of China",
	"Tanzania, United Republic of": "Tanzania, United Republic of",
	"Thailand": "Thailand",
	"Timor-Leste": "Timor-Leste",
	"Togo": "Togo",
	"Tokelau": "Tokelau",
	"Tonga": "Tonga",
	"Trinidad and Tobago": "Trinidad and Tobago",
	"Tunisia": "Tunisia",
	"Turkey": "Turkey",
	"Turks and Caicos Islands": "Turks and Caicos Islands",
	"Tuvalu": "Tuvalu",
	"Ukraine": "Ukraine",
	"United Arab Emirates": "United Arab Emirates",
	"United Kingdom": "United Kingdom",
	"United States": "United States",
	"United States Minor Outlying Islands": "United States Minor Outlying Islands",
	"Uruguay": "Uruguay",
	"Vanuatu": "Vanuatu",
	"Venezuela": "Venezuela",
	"Viet Nam": "Viet Nam",
	"Virgin Islands, British": "Virgin Islands, British",
	"Virgin Islands, U.S.": "Virgin Islands, U.S.",
	"Wallis And Futuna": "Wallis And Futuna",
	"Western Sahara": "Western Sahara",
	"Yemen": "Yemen",	
	"Rodent": "Rodent",
	"Ungulate": "Ungulate",
	"Cat": "Cat",
	"Rabbit and Hare": "Rabbit and Hare",
	"Mongoose and Weasel": "Mongoose and Weasel",
	"Dog and Fox": "Dog and Fox",
	"Mammal (Other)": "Mammal (Other)",
	"Reptile": "Reptile",
	"Bird": "Bird",
	"Amphibian": "Amphibian",
	"Primate": "Primate",
	"To Be Confirmed": "To Be Confirmed",
	"In Progress": "In Progress",
	"Incomplete": "Incomplete",
	"Failed": "Failed",
	"Planned": "Planned",
	"Successful": "Successful",
	"Successful (all)": "Successful (all)",
	"Successful (non-reinvaded)": "Successful (non-reinvaded)",
	"Successful (reinvaded)": "Successful (reinvaded)",
	"Unknown": "Unknown",
	"Incursion": "Incursion",
	"Trial or Research only": "Trial or Research only",
	"Disease": "Disease",
	"Hunting": "Hunting ",
	"Trapping": "Trapping",
	"Toxicant": "Toxicant",
	"Other": "Other",
	"Cane Toad": "Cane Toad",
	"Coqui Antillano/ Lesser Antillean Whistling Frog": "Coqui Antillano/ Lesser Antillean Whistling Frog",
	"Cuban Tree-Frog": "Cuban Tree-Frog",
	"Eastern Narrowmouth Toad": "Eastern Narrowmouth Toad",
	"Golden-Bell Frog": "Golden-Bell Frog",
	"Green Frog": "Green Frog",
	"Greenhouse Frog": "Greenhouse Frog",
	"Indian Bullfrog": "Indian Bullfrog",
	"North American Bullfrog": "North American Bullfrog",
	"Pig Frog": "Pig Frog",
	"Puerto Rican Coqui": "Puerto Rican Coqui",
	"Ranita X": "Ranita X",
	"Scinax Ruber": "Scinax Ruber",
	"Southern Leopard Frog": "Southern Leopard Frog",
	"Squirrel Tree Frog": "Squirrel Tree Frog",
	"Unnamed Frog 1": "Unnamed Frog 1",
	"Unnamed Frog 2": "Unnamed Frog 2",
	"Unspecified Frog": "Unspecified Frog",
	"Whistling Frog": "Whistling Frog",
	"American Crow": "American Crow",
	"Australasian Grebe": "Australasian Grebe",
	"Australian Magpie": "Australian Magpie",
	"Black Drongo": "Black Drongo",
	"Black Francolin": "Black Francolin",
	"Brown-necked Raven": "Brown-necked Raven",
	"Canada Goose": "Canada Goose",
	"Cattle Egret": "Cattle Egret",
	"Chinese Hwamei": "Chinese Hwamei",
	"Chukor": "Chukor",
	"Common Myna": "Common Myna",
	"Common Pheasant": "Common Pheasant",
	"Common Starling": "Common Starling",
	"Common Waxbill": "Common Waxbill",
	"Crimson Rosella": "Crimson Rosella",
	"Domestic Chicken": "Domestic Chicken",
	"Eastern Rosella": "Eastern Rosella",
	"Eurasian Collared Dove": "Eurasian Collared Dove",
	"Eurasian Tree Sparrow": "Eurasian Tree Sparrow",
	"European Goldfinch": "European Goldfinch",
	"European Greenfinch": "European Greenfinch",
	"Fishers Lovebird": "Fishers Lovebird",
	"Green Junglefowl": "Green Junglefowl",
	"Grey partridge": "Grey partridge",
	"House Crow": "House Crow",
	"House Sparrow": "House Sparrow",
	"Island Collared Dove": "Island Collared Dove",
	"Japanese Bush-warbler": "Japanese Bush-warbler",
	"Japanese White-eye": "Japanese White-eye",
	"Jungle Crow": "Jungle Crow",
	"Jungle Myna": "Jungle Myna",
	"Kiskadees": "Kiskadees",
	"Laughing Kookaburra": "Laughing Kookaburra",
	"Madagascar Red Fody": "Madagascar Red Fody",
	"Mallard": "Mallard",
	"Monk Parakeet": "Monk Parakeet",
	"Muscovy Duck": "Muscovy Duck",
	"Nankeen Kestrel": "Nankeen Kestrel",
	"Night Heron": "Night Heron",
	"Northern Cardinal": "Northern Cardinal",
	"Orange-cheeked Waxbill": "Orange-cheeked Waxbill",
	"Red Junglefowl": "Red Junglefowl",
	"Red-Billed Leiothrix": "Red-Billed Leiothrix",
	"Red-masked Parakeet": "Red-masked Parakeet",
	"Red-vented Bulbul": "Red-vented Bulbul",
	"Red-whiskered Bulbul": "Red-whiskered Bulbul",
	"Ringed Turtle-dove": "Ringed Turtle-dove",
	"Rock Dove": "Rock Dove",
	"Rose-ringed Parakeet": "Rose-ringed Parakeet",
	"Ruddy Duck": "Ruddy Duck",
	"Shiny Cowbird": "Shiny Cowbird",
	"Silvereye": "Silvereye",
	"Smooth-billed Ani": "Smooth-billed Ani",
	"Southern Boobook": "Southern Boobook",
	"Swamp Harrier": "Swamp Harrier",
	"Tiuque / Chimango Caracara": "Tiuque / Chimango Caracara",
	"Unspecified Birds": "Unspecified Birds",
	"Unspecified Gull": "Unspecified Gull",
	"Unspecified Peacock": "Unspecified Peacock",
	"Weka": "Weka",
	"White-rumped Shama": "White-rumped Shama",
	"White-Winged Dove": "White-Winged Dove",
	"Wild Turkey": "Wild Turkey",
	"Yellow-crowned Amazon": "Yellow-crowned Amazon",
	"Australian Masked-owl": "Australian Masked-owl",
	"Barn Owl": "Barn Owl",
	"Great Horned Owl": "Great Horned Owl",
	"Harris's Hawk": "Harris's Hawk",
	"African Civet": "African Civet",
	"Caracal": "Caracal",
	"Domestic Cat": "Domestic Cat",
	"Malay Civet": "Malay Civet",
	"Wildcat": "Wildcat",
	"Arctic Fox": "Arctic Fox",
	"Bat-Eared Fox": "Bat-Eared Fox",
	"Cape Fox": "Cape Fox",
	"Dingo": "Dingo",
	"Domestic Dog": "Domestic Dog",
	"Grey Wolf": "Grey Wolf",
	"Red Fox": "Red Fox",
	"Silver-grey Fox": "Silver-grey Fox",
	"Unspecified Fox": "Unspecified Fox",
	"African Sharptooth Catfish": "African Sharptooth Catfish",
	"Asian Snakehead": "Asian Snakehead",
	"Bighead Carp": "Bighead Carp",
	"Blue Tilapia": "Blue Tilapia",
	"Brown Trout": "Brown Trout",
	"Carp": "Carp",
	"Congo Tilapia": "Congo Tilapia",
	"Eastern mosquitofish": "Eastern mosquitofish",
	"Goldfish": "Goldfish",
	"Grass Carp": "Grass Carp",
	"Green Swordtail": "Green Swordtail",
	"Guppy": "Guppy",
	"Largemouth Bass": "Largemouth Bass",
	"Mozambique Tilapia": "Mozambique Tilapia",
	"Nile Perch": "Nile Perch",
	"Perche africaine": "Perche africaine",
	"Rainbow Trout": "Rainbow Trout",
	"Red Lionfish": "Red Lionfish",
	"Redbelly Tilapia": "Redbelly Tilapia",
	"Salmon Trout": "Salmon Trout",
	"Silver Carp": "Silver Carp",
	"Silverside": "Silverside",
	"Snakehead Fish": "Snakehead Fish",
	"Snakehead Murrel": "Snakehead Murrel",
	"Unspecified Catfish": "Unspecified Catfish",
	"Unspecified Cyprinid Fish": "Unspecified Cyprinid Fish",
	"Unspecified Fish": "Unspecified Fish",
	"Unspecified Snakehead Fish": "Unspecified Snakehead Fish",
	"Unspecified Tilapia Fish": "Unspecified Tilapia Fish",
	"Argentine Ant": "Argentine Ant",
	"Big-headed Ant": "Big-headed Ant",
	"Cactus Moth": "Cactus Moth",
	"Common Greenbottle Fly": "Common Greenbottle Fly",
	"Common Wasp": "Common Wasp",
	"Ectoparasitic botfly": "Ectoparasitic botfly",
	"Fire Ant": "Fire Ant",
	"Freshwater Shrimp": "Freshwater Shrimp",
	"Garlic Snail": "Garlic Snail",
	"Honey Bee": "Honey Bee",
	"Louisiana Crayfish": "Louisiana Crayfish",
	"Parasitic Nematode": "Parasitic Nematode",
	"Pharaoh Ant": "Pharaoh Ant",
	"Small Fire Ant": "Small Fire Ant",
	"Two-spotted Leafhopper": "Two-spotted Leafhopper",
	"Unspecified Ants": "Unspecified Ants",
	"Unspecified Cockroach": "Unspecified Cockroach",
	"Unspecified Fire Ants": "Unspecified Fire Ants",
	"Unspecified Insects": "Unspecified Insects",
	"Unspecified Wasps": "Unspecified Wasps",
	"Western Yellowjacket": "Western Yellowjacket",
	"Yellow Crazy Ant": "Yellow Crazy Ant",
	"Yellow Jacket Wasp": "Yellow Jacket Wasp",
	"Yellow Paper Wasp": "Yellow Paper Wasp",
	"Agile Wallaby": "Agile Wallaby",
	"Algerian Hedgehog": "Algerian Hedgehog",
	"American Beaver": "American Beaver",
	"American Red Squirrel": "American Red Squirrel",
	"Amur Hedgehog": "Amur Hedgehog",
	"Arctic Ground Squirrel": "Arctic Ground Squirrel",
	"Asian Elephant": "Asian Elephant",
	"Asian Palm Civet": "Asian Palm Civet",
	"Bahama Hutia": "Bahama Hutia",
	"Barbary Ground Squirrel": "Barbary Ground Squirrel",
	"Black-striped Wallaby": "Black-striped Wallaby",
	"Brown's Pademelon": "Brown's Pademelon",
	"Cape Serotine Bat": "Cape Serotine Bat",
	"Common Brushtail Possum": "Common Brushtail Possum",
	"Common Genet": "Common Genet",
	"Common Marmoset": "Common Marmoset",
	"Common Opossum": "Common Opossum",
	"Common Spotted Cuscus": "Common Spotted Cuscus",
	"Common Tenrec": "Common Tenrec",
	"Eastern Chipmunk": "Eastern Chipmunk",
	"Eastern Quoll": "Eastern Quoll",
	"Egyptian Fruit Bat": "Egyptian Fruit Bat",
	"Elegant Fat-Tailed Mouse Opossum": "Elegant Fat-Tailed Mouse Opossum",
	"Eurasian Red Squirrel": "Eurasian Red Squirrel",
	"Gray Squirrel": "Gray Squirrel",
	"Hoary Marmot": "Hoary Marmot",
	"Japanese Macaque": "Japanese Macaque",
	"Javanese Porcupine": "Javanese Porcupine",
	"Large Opossum": "Large Opossum",
	"Nine-banded Armadillo": "Nine-banded Armadillo",
	"Northern Common Cuscus": "Northern Common Cuscus",
	"Pallas Squirrel": "Pallas Squirrel",
	"Parma Wallaby": "Parma Wallaby",
	"Raccoon": "Raccoon",
	"Red-necked Wallaby": "Red-necked Wallaby",
	"Rock Hyrax": "Rock Hyrax",
	"Siberian Chipmunk": "Siberian Chipmunk",
	"Small Indian Civet": "Small Indian Civet",
	"South American Coati": "South American Coati",
	"Southern Common Cuscus": "Southern Common Cuscus",
	"Striped Palm Squirrel": "Striped Palm Squirrel",
	"Swamp Wallaby": "Swamp Wallaby",
	"Tammar Wallaby": "Tammar Wallaby",
	"Tasmanian Bettong": "Tasmanian Bettong",
	"Unspecified Mammals": "Unspecified Mammals",
	"Unspecified possum": "Unspecified possum",
	"Unspecified Squirrel": "Unspecified Squirrel",
	"Unspecified Tenrec": "Unspecified Tenrec",
	"Virginia Opossum": "Virginia Opossum",
	"West European Hedgehog": "West European Hedgehog",
	"White-tailed Antelope Squirrel": "White-tailed Antelope Squirrel",
	"Zanj Sun Squirrel": "Zanj Sun Squirrel",
	"American Mink": "American Mink",
	"Beech Marten": "Beech Marten",
	"Cape Grey Mongoose": "Cape Grey Mongoose",
	"Egyptian Mongoose (Large Grey Mongoose)": "Egyptian Mongoose (Large Grey Mongoose)",
	"European Pine Marten": "European Pine Marten",
	"European Polecat": "European Polecat",
	"Ferret": "Ferret",
	"Indian Grey Mongoose": "Indian Grey Mongoose",
	"Japanese Marten": "Japanese Marten",
	"Japanese Weasel": "Japanese Weasel",
	"Least Weasel": "Least Weasel",
	"Siberian Weasel": "Siberian Weasel",
	"Small Asian (Javan) Mongoose": "Small Asian (Javan) Mongoose",
	"Small Indian Mongoose": "Small Indian Mongoose",
	"Stoat / Ermine": "Stoat / Ermine",
	"Unspecified Mongoose": "Unspecified Mongoose",
	"Unspecified Weasel": "Unspecified Weasel",
	"Water Mongoose (Marsh Mongoose)": "Water Mongoose (Marsh Mongoose)",
	"Yellow Mongoose": "Yellow Mongoose",
	"NONE": "NONE",
	"Crab-eating Macaque": "Crab-eating Macaque",
	"Green Monkey / Grivet": "Green Monkey / Grivet",
	"Grivet Monkey": "Grivet Monkey",
	"Mona Monkey": "Mona Monkey",
	"Rhesus Macaque": "Rhesus Macaque",
	"Southern Pig-tailed Macaque": "Southern Pig-tailed Macaque",
	"Taiwan Macaque": "Taiwan Macaque",
	"Unspecified Macaque": "Unspecified Macaque",
	"Black-tailed Jack Rabbit": "Black-tailed Jack Rabbit",
	"Brush-tailed Rock Wallaby": "Brush-tailed Rock Wallaby",
	"Cape Hare": "Cape Hare",
	"Cottontail": "Cottontail",
	"European Hare": "European Hare",
	"European Rabbit": "European Rabbit",
	"Indian Hare": "Indian Hare",
	"Snowshoe Hare": "Snowshoe Hare",
	"Unspecified Rabbit": "Unspecified Rabbit",
	"Afro-American House Gecko": "Afro-American House Gecko",
	"Barbados Anole": "Barbados Anole",
	"Bronze Anole": "Bronze Anole",
	"Brown Anole": "Brown Anole",
	"Common Agama": "Common Agama",
	"Common House Gecko": "Common House Gecko",
	"Common Iguana": "Common Iguana",
	"Cuban Brown Anole": "Cuban Brown Anole",
	"Cuban Green Anole": "Cuban Green Anole",
	"Curious Skink": "Curious Skink",
	"Diamondback Terrapin": "Diamondback Terrapin",
	"Eastern Glass Lizard": "Eastern Glass Lizard",
	"Four-fingered Skinks": "Four-fingered Skinks",
	"Giant Black and White Tegu": "Giant Black and White Tegu",
	"Gould's Monitor Lizard": "Gould's Monitor Lizard",
	"Green Anole ": "Green Anole ",
	"Green Tree Skink": "Green Tree Skink",
	"Grenada Tree Anole": "Grenada Tree Anole",
	"Haitian Big-scaled Sphaero": "Haitian Big-scaled Sphaero",
	"Heath Monitor Lizard": "Heath Monitor Lizard",
	"Inagua Slider": "Inagua Slider",
	"Indian Monitor Lizard": "Indian Monitor Lizard",
	"Indo-Pacific House Gekko": "Indo-Pacific House Gekko",
	"Italian Wall Lizard": "Italian Wall Lizard",
	"Jamaican Anole": "Jamaican Anole",
	"Knight Anole": "Knight Anole",
	"Land Iguana": "Land Iguana",
	"Madagascar Giant Day Gecko": "Madagascar Giant Day Gecko",
	"Mangrove Monitor Lizard": "Mangrove Monitor Lizard",
	"Mourning Gecko": "Mourning Gecko",
	"Mutilating Gecko": "Mutilating Gecko",
	"Oceanic Gecko": "Oceanic Gecko",
	"Puerto Rican Anole": "Puerto Rican Anole",
	"Rainbow Skink": "Rainbow Skink",
	"Red-Eared Slider": "Red-Eared Slider",
	"Red-footed Tortoise": "Red-footed Tortoise",
	"Reissi Gecko": "Reissi Gecko",
	"Saint Vincent's Bush Anole": "Saint Vincent's Bush Anole",
	"Savannah Monitor Lizard": "Savannah Monitor Lizard",
	"Shingleback": "Shingleback",
	"Spectacled Caiman": "Spectacled Caiman",
	"Sugar glider": "Sugar glider",
	"Tokay Gecko": "Tokay Gecko",
	"Tuberculosus Gecko": "Tuberculosus Gecko",
	"Underwood's Spectacled Tegu": "Underwood's Spectacled Tegu",
	"Unspecified Slider": "Unspecified Slider",
	"Warwick Lizard": "Warwick Lizard",
	"Watts Anole": "Watts Anole",
	"Yellow-bellied Slider": "Yellow-bellied Slider",
	"Barbour's Tropical Racer": "Barbour's Tropical Racer",
	"Boa Constrictor": "Boa Constrictor",
	"Brahminy Blind Snake": "Brahminy Blind Snake",
	"Brown Snake": "Brown Snake",
	"Brown Tree Snake": "Brown Tree Snake",
	"Burmese Python": "Burmese Python",
	"Common Garter Snake": "Common Garter Snake",
	"Eastern Box Snake": "Eastern Box Snake",
	"Eastern Rat Snake": "Eastern Rat Snake",
	"Red Cornsnake": "Red Cornsnake",
	"Ring-necked Snake": "Ring-necked Snake",
	"Unspecified Snake": "Unspecified Snake",
	"Algerian Mouse": "Algerian Mouse",
	"Arctic Lemming": "Arctic Lemming",
	"Asian House Rat": "Asian House Rat",
	"Asian House Shrew": "Asian House Shrew",
	"Black Rat": "Black Rat",
	"Brazilian Agouti": "Brazilian Agouti",
	"Brown / Norway Rat": "Brown / Norway Rat",
	"Brown Country Rat": "Brown Country Rat",
	"Cactus Mouse": "Cactus Mouse",
	"Cairo Spiny Mouse": "Cairo Spiny Mouse",
	"Capybara": "Capybara",
	"Central American Agouti": "Central American Agouti",
	"Domesticated Guinea Pig": "Domesticated Guinea Pig",
	"Gambian Rat": "Gambian Rat",
	"Garden Dormouse": "Garden Dormouse",
	"Greater Bandicoot Rat": "Greater Bandicoot Rat",
	"Greater White-toothed Shrew": "Greater White-toothed Shrew",
	"Himalayan Rat": "Himalayan Rat",
	"House Mouse": "House Mouse",
	"Javanese Shrew": "Javanese Shrew",
	"Lesser Dwarf Shrew": "Lesser Dwarf Shrew",
	"Lowland Paca": "Lowland Paca",
	"Madagascan Pygmy Shrew": "Madagascan Pygmy Shrew",
	"Mexican Agouti": "Mexican Agouti",
	"North American Deermouse": "North American Deermouse",
	"Northern Baja Deermouse": "Northern Baja Deermouse",
	"Nutria": "Nutria",
	"Olive Grass Mouse": "Olive Grass Mouse",
	"Polynesian Rat": "Polynesian Rat",
	"Pygmy Mouse": "Pygmy Mouse",
	"Red-tailed Squirrel": "Red-tailed Squirrel",
	"Ricefield Rat": "Ricefield Rat",
	"Santa Lucia Agouti": "Santa Lucia Agouti",
	"Spiny Rat": "Spiny Rat",
	"Unspecified Agouti": "Unspecified Agouti",
	"Unspecified Mice": "Unspecified Mice",
	"Unspecified porcupine": "Unspecified porcupine",
	"Unspecified Rats": "Unspecified Rats",
	"Unspecified Rodent": "Unspecified Rodent",
	"White-toothed Pygmy Shrew": "White-toothed Pygmy Shrew",
	"Woodmouse": "Woodmouse",
	"Alpine Chamois": "Alpine Chamois",
	"Babirusa": "Babirusa",
	"Banteng": "Banteng",
	"Barbary Sheep": "Barbary Sheep",
	"Barking Deer": "Barking Deer",
	"Big-horn Sheep": "Big-horn Sheep",
	"Blackbuck": "Blackbuck",
	"Bontebok": "Bontebok",
	"Buffalo": "Buffalo",
	"Bush Pig": "Bush Pig",
	"Cape Grysbok": "Cape Grysbok",
	"Chital (Barking Deer)": "Chital (Barking Deer)",
	"Common Eland": "Common Eland",
	"Domestic Cow": "Domestic Cow",
	"Domestic Pig": "Domestic Pig",
	"Domestic Sheep": "Domestic Sheep",
	"Donkey": "Donkey",
	"Elk": "Elk",
	"Eurasian Elk": "Eurasian Elk",
	"Fallow Deer": "Fallow Deer",
	"Giant Eland": "Giant Eland",
	"Goat": "Goat",
	"Himalayan Tahr": "Himalayan Tahr",
	"Hog Deer": "Hog Deer",
	"Horse": "Horse",
	"Javan Rusa": "Javan Rusa",
	"Llama": "Llama",
	"Mouflon": "Mouflon",
	"Mountain Goat": "Mountain Goat",
	"Mountain Sheep": "Mountain Sheep",
	"Mule Deer": "Mule Deer",
	"Nilgai": "Nilgai",
	"One-humped Camel": "One-humped Camel",
	"Peccary": "Peccary",
	"Philippine Sambar Deer": "Philippine Sambar Deer",
	"Red Deer": "Red Deer",
	"Reindeer": "Reindeer",
	"Rusa Deer": "Rusa Deer",
	"Sambar": "Sambar",
	"Sika Deer": "Sika Deer",
	"Springbok": "Springbok",
	"Steenbuck": "Steenbuck",
	"Sulawesi Warty Pig": "Sulawesi Warty Pig",
	"Tatabro": "Tatabro",
	"Unspecified Deer": "Unspecified Deer",
	"Unspecified Ungulate": "Unspecified Ungulate",
	"Water Buffalo": "Water Buffalo",
	"White-tailed Deer": "White-tailed Deer",
	"Wild Boar/Pig": "Wild Boar/Pig",
	"Wild Goat": "Wild Goat",
	"Zebu": "Zebu",
	"References": "References",
	"Data Quality": "Data Quality",
	"Publication": "Publication",
	"Grey literature": "Grey literature",
	"Online Database": "Online Database",
	"Popular Press": "Popular Press",
	"Other": "Other",
	"Island Eradication Type": "Island Eradication Type",
	"Whole Island": "Whole Island",
	"Restricted range": "Restricted range",
	"Fence area": "Fence area",
	"Incursion": "Incursion"
}

var config_byId_en = {
	"link_about": "About",
	"link_news": "News",
	"link_disclaimer": "Disclaimer",
	"link_terms": "Terms of Use",
	"link_help": "How to Help",
	"link_partners": "Partners",
	"link_contact": "Contact",
	"link_more": "More Info",
	"app_language_text": "Language:",
	"language_english_text": "English",
	"language_spanish_text": "Spanish",
	"splash_language_text": "Language:",
	"splash_language_english": "English",
	"splash_language_spanish": "Spanish",
	"cisr": "built by the <a target=\"_blank\" href=\"http://spatial.cisr.ucsc.edu\">center for integrated spatial research (cisr)</a> @ <a target=\"_blank\" href=\"http://www.ucsc.edu\">ucsc</a>",
	"graphicText": "Graphic:",
	"rectangle": "... by Rectangle",
	"polygon":  "... by Polygon",
	"basemap_basic": "Basic",
	"basemap_satellite": "Satellite",
	"basemap_topographic": "Topographic",
	"printOptionsTextNode": "Export Map",
	"printButton": "Export",
	"csvOptionsTextNode": "Export to CSV",
	"csvButton": "Export",
	"regionSelect_label": "Region:",
	"countrySelect_label": "Country:",
	"islandSelect_label": "Island:",
	"invasiveTypeSelect_label": "Type:",
	"invasiveScientificSelect_label": "Scientific Name:",
	"invasiveCommonSelect_label": "Common Name:",
	"inv_sci_label": "Scientific Name",
	"inv_com_label": "Common Name",	
	"eradicationStatusSelect_label": "Status:",
	"eradicationMethodSelect_label": "Primary Method:",
	"csvTermsCheck_label": "I agree to the conditions outlined in the Terms of Use above.",
	"printTermsCheck_label": "I agree to the conditions outlined in the Terms of Use above.",	
	"queryDefinition": "Filter:",
	"r_islands_text": "Number of islands",
	"invasives_sum_text": "eradications",
	"r_invasives_text": "Number of species",
	"r_type_animal": "Type (Animal)",
	"r_status_eradication": "Status (Eradication)",
	"islandTitle": "No Island Selected",
	"table_header_text": "Table",
	"noThumbnails": "No thumbnail images found",
	"aboutContent": "<span class=\"aboutHeader\">What is the Database of Island Invasive Species Eradications?</span><br/>Islands  are the epicenter of the current global extinction crisis and invasive  vertebrates are the leading cause of extinction on islands. Removing invasive  vertebrates from islands is a well-established tool to protect and restore  island ecosystems and prevent extinctions.<p>The  Database  of  Island Invasive Species Eradications compiles all of the historical and current invasive vertebrate eradications  on islands. Data from each project includes information on the island, methods  used in the eradication and contact information   for people knowledgeable about the eradication.</p><p>Our  hope is that the database will help by facilitating:</p><ul type=\"circle\"><li>Knowledge sharing: Improving transfer of knowledge between existing eradication practitioners, and providing contacts for each eradication to facilitate communication between experienced eradicators and those seeking assistance </li><li>Technique evaluation: Tracking eradication attempts to analyse where, how and who is undertaking these efforts, which techniques are successful and highlighting invasive species for which techniques are deficient. </li><li>Fund raising: this database is a valuable tool for fund raising by allowing practitioners to contextualize proposed island eradication projects against the global scope of this technique and historical eradication attempts. </li></ul>",
	"chartNodeText":"<b>Figure 1</b>. Cumulative number of successful eradications by year since 1950.",
	"howToCite": "<span class=\"aboutHeader\">How To Cite?</span> <br/>DIISE, 2015. The Database of Island Invasive Species Eradications, developed by Island Conservation, Coastal Conservation Action Laboratory UCSC, IUCN SSC Invasive Species Specialist Group, University of Auckland and Landcare Research New Zealand. http://diise.islandconservation.org.<br/>",
	"aboutReferenceHeader": "References",
	"aboutFunding": "The online Database of Island Invasive Species Eradications was built with the support of The David and Lucille Packard Foundation, the National Fish and Wildlife Foundation, and the Global Environment Facility.",
	"errorContent": "Island Conservation endeavor to maintain the most accurate and up-to-date data at all times. However, if errors or omissions are identified, the user should notify Island Conservation <a href=\"mailto:science@islandconservation.org\">science@islandconservation.org</a> so that they can be corrected in future releases of the data. Please mark all correspondence: \"Database of Islands and Invasive Species Eradications\".",
	"disclaimerContent": "Island Conservation make no warranties or representations, express or implied, regarding the use of the material appearing in this dataset with regard to their correctness, reliability, accuracy, or otherwise. The material and geographic designations in this dataset do not imply the expressions of any opinion whatsoever on the part of Island Conservation concerning the legal status of any country, territory or area, nor concerning the delimitation of its frontiers or boundaries. Neither Island Conservation nor its affiliated or related entities or its content providers shall be responsible or liable to any person, firm or corporation for any loss, damage, injury, claim or liability of any kind or character based on or resulting from any information contained in the dataset. Island Conservation may update or make changes to the data provided at any time without notice; however, Island Conservation makes no commitment to update the information contained therein.",
	"termsOfUseContent": "<ol><li>The data are supplied only for conservation purposes, scientific analysis or research.</li><li>The recipient of the data will provide a full and appropriate acknowledgement and citation in any materials or publications derived in part or in whole from the data; relevant citation details will be provided with each dataset. For any publications making substantial use of the data, Island Conservation welcomes the opportunity for co-authorship, collaboration and to comment prior to publication. Expressions of interest can be sent to <a href=\"mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE\">science@islandconservation.org</a>.</li><li>Reproduction of the dataset or products derived from it, either whole or in part, for commercial purposes is prohibited without prior written permission from Island Conservation. For the purposes of these Terms of Use, “commercial purposes” means a) any use by, on behalf of, or to inform or assist the activities of, a commercial entity (an entity that operates ‘for profit’) or b) use by any non-profit entity for the purposes of revenue generation. If you require permission please contact <a href=\"mailto:science@islandconservation.org?Subject=Commercial%20use%20of%20DIISE\">science@islandconservation.org</a>.</li><li>The recipient will not publish the data in their original format, either whole or in part, on a website, FTP site, CD, memory stick or any other media. The recipient should provide a link to the original data source location on the IUCN Invasive Species Specialist Group website where appropriate.</li><li>Use of these data does not constitute endorsement by Island Conservation of any derived products, reports or analyses. The Island Conservation logo must not be used on any derived products, reports or analyses, or supporting materials, without express permission.</li><li>Use of these data does not constitute endorsement by Island Conservation of any derived products, reports or analyses. The Island Conservation logo must not be used on any derived products, reports or analyses, or supporting materials, without express permission.</li><li>Island Conservation reserves the right to comment on the accuracy of representation of the data in material produced by a recipient.</li><li>Island Conservation endeavor to maintain accurate and up-to-date data at all times, but can accept no responsibility for the consequences of errors or omissions in the data, for misuse of the data by any organization or individual, or for any damage done to computing systems into which the data are entered (see Disclaimer).</li><li>Either an electronic or two paper copies of all products published using data supplied by Island Conservation will be sent, free of charge, to the data authors via: Island Conservation, 100 Shaffer Road, Santa Cruz CA USA 95060 or via email to <a href=\"mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE\">science@islandconservation.org</a>.</li></ol>",
	"newsContent": "<b>Version 2015.1</b>: Major updates/revisions to data undertaken.",
	"partners_text": "People, organizations, and agencies that have helped develop the Database of Island Invasive Species Eradications",
	"userInfoTermsTitle": "Please Register Your Details", 
	"purposeText": "Intended use of the data"
}

var config_byDijitId_en = {
	"searchContentDiv": "Search",
	"resultsContentDiv": "Results",
	"islandContentDiv": "Island Details",
	"geography": "... by geographic location",
	"invasive": "... by invasive species",
	"eradication": "... by eradication detail",
	"searchButton": "Run Search", 
	"clearButton": "Clear Search",
	"printButton": "Export",
	"csvButton": "Export",
	"infoDetails": "Island",
	"infoInvasive": "Eradication(s)",
	"eradicationDetails": "Details of Eradication Record",
	"about": "About the Database of Island Invasive Species Eradications",
	"news": "News",
	"disclaimer": "Disclaimer",
	"termsOfUse": "Terms of Use",
	"errors": "How to Help",
	"partners": "Partners",	
	"Letter": "Letter",
	"csvContinueButton": "Continue",
	"printContinueButton": "Continue",
	"splash_language_spanish_tooltip": "Spanish",
	"splash_language_english_tooltip": "English",
	"searchTool_tooltip": "Click to open/close the custom Search window.",
	"resultsTool_tooltip": "Click to open/close the Results window.",
	"islandsTool_tooltip": "Click to open/close the Island Details window.",
	"csvTool_tooltip": "Click to export and download a .csv file of the results table.",
	"printTool_tooltip": "Click to export and download a high-resolution map.",
	"basemap_tooltip": "Click to change the underlying basemap.",
	"overview_tooltip": "Click to open/close the Overview Map window.",
	"zoomfull_tooltip": "Click to zoom out to the full extent of the map.",
	"zoomin_tooltip": "Click to zoom in to the map using a custom drawn extent.", 
	"splitter_tooltip": "Click + drag to increase or decrease the viewable table.",
	"close_tooltip": "Click to hide or show the table.",
	"search_tooltip": "Build a custom search. Click + drag to move the dialog to a new position.",
	"results_tooltip": "Results from your custom search. Click + drag to move the dialog to a new position.",
	"island_tooltip": "Detailed information on a specific island. Click + drag to move the dialog to a new position.",
	"r_breeding_tooltip": "Shift + Click for complete definitions of Breeding Status.",
	"experts_tooltip": "Click for a list of contributing experts and the DIISE data collection team.",
	"donate_tooltip": "Click to donate towards DIISE development via the Island Conservation Paypal site.",
	"island_invasives_tooltip": "All invasive species on an island.",
	"userName": "First &amp; Last Name",
	"email": "E-mail",
	"org": "Organization",
	"country": "Country"
}

var config_byValues_es = {
	"species_record_tooltip": "Pulse una celda para ver más detalles sobre el registro",
	"islands_record_tooltip": "Pulse una celda para desplazarse a la isla en el mapa",
	"tib_record_tooltip": "Cualquier especies amenazadas de la isla desde la base de datos de Biodiversidad Amenazada en Islas (TIB).",
	"no_filter": "No hay filtros de búsqueda elegido. Por favor, selecciona los artículos en el panel de búsqueda para filtrar por ...",
	"Error selecting the item in the data table": "Error de seleccionar el elemento de la tabla de datos",
	"Download": "Descargar",
	"Export": "Exportar",
	"Export Map": "Exportar el Mapa",
	"Export to CSV": "Exportar a CSV",	
	"Exporting Map": "Exportar el Mapa",
	"Exporting to CSV": "Exportar a CSV",
	"Download Map": "Descargar el Mapa",
	"Download CSV": "Descargar CSV",
	"Processing": "Procesar",
	"No thumbnail images found": "No se encontraron imágenes 'thumbnail'",
	"Filter": "Filtro",
	"Graphic": "Grafico",
	"Species Details": "Detalles Especies",
	"Location Details": "Detalles de Ubicación",
	"Eradication Details": "Detalles de la Erradicación",
	"Contact Details": "Datos de Contacto",
	"Common Name": "Nombre Común",
	"Scientific Name": "Nombre Científico",
	"Type (Animal)": "Tipo (Animal)",
	"Year of Introduction": "Año de Introducción",
	"Latitude": "Latitud",
	"Longitude": "Longitud",
	"Status (Eradication)": "Estado (Erradicación)",
	"Eradication Status": "Estado (Erradicación)",
	"Island Eradication Type" : "Tipo de Erradicación de Isla",
	"Primary Eradication Method": "Método Principal",
	"Secondary Eradication Method": "Método Secundario",
	"Tertiary Eradication Method": "Método Terciaria",
	"Eradication Start Date": "Fecha Inicio de Erradicación ",
	"Eradication End Date": "Fecha Final de Erradicación",	
	"Primary Baiting Method": "Cebo Primario",
	"Secondary Baiting Method": "Cebo Secundario",
	"Eradication Method Details": "Erradicación Método Detalles",
	"Trapping Method Details": "Método de Captura Detalles",
	"Method Description": "Método Descripción",
	"Primary Toxicant": "Tóxico Primario",
	"Secondary Toxicant": "Tóxico Secundario",
	"Cost": "Costo",
	"Eradication Contact": "Contacto Erradicación",
	"Contact Email": "Correo Electrónico de Contacto",
	"Contact Organization": "Organización Contacto",
	"Organization Website": "Organización Sitio Web",
	"Island Code": "Código de Isla",
	"Island Name": "Nombre de Isla",
	"Name": "Nombre",
	"Coordinates": "Coordenadas",
	"Region": "Región",
	"Country": "País",
	"Archipelago": "Archipiélago",
	"Area (sq km)": "Área (km2)",	
	"Human Population": "Población Humana",
	"Invasive Species": "Especies invasoras",
	"Threatened Species": "Especies amenazadas",
	"Threatened": "Amenazado",
	"eradication": "erradicación",
	"eradications": "erradicaciones",
	"Eradications": "Erradicaciones",
	"search in the TIB": "búsqueda en el TIB",
	"None": "Ninguno",
	"none": "ninguno",
	"yes": "si",
	"no": "no",	
	"Populations": "Poblaciónes",
	"populations": "poblaciónes",
	"population": "población",
	"online": "en línea",
	"no common name": "sin nombre Común",
	"unknown": "desconocido",
	"Status": "Estado",
	"Year": "Año",
	"chart: x-axis": "Año",
	"chart: y-axis": "Número de erradicaciones exitosas",	
	" -- all -- ": " -- todo -- ",
	"Arctic Ocean - North Canada": "Oceano Artico-Canada del Norte",
	"Atlantic Ocean - North": "Océano Atlántico - Norte",
	"Atlantic Ocean - South": "Océano Atlántico - Sur",
	"Baltic sea": "Mar Baltico",
	"Caribbean": "Caribe",
	"Indian Ocean - East": "Océano Indico - Este",
	"Indian Ocean - West": "Océano Indico- Oeste",
	"Mediterranean": "Mediterráneo",
	"Nusantarian Sea": "Mar Nusantario",
	"Pacific Ocean - North East": "Océano Pacífico - Noreste",
	"Pacific Ocean - North West": "Océano Pacifico - Noroeste",
	"Pacific Ocean - South East": "Océano Pacifico- Sureste",
	"Pacific Ocean - South West": "Océano Pacifico-Suroeste",
	"Rodent": "Roedor",
	"Ungulate": "Ungulado",
	"Cat": "Gato",
	"Rabbit and Hare": "Conejo y liebre",
	"Mongoose and Weasel": "Mangosta y Comadreja",
	"Dog and Fox": "Perro y Zorro",
	"Mammal (Other)": "Mamífero (otro)",
	"Reptile": "Reptil",
	"Amphibian": "Anfibio",
	"Bird": "Ave",
	"Primate": "Primate",
	"To Be Confirmed": "Ser Confirmado",
	"In Progress": "En Proceso",
	"Incomplete": "Incompleto",
	"Failed": "Fallido",
	"Planned": "Planificado",
	"Successful": "Existoso",
	"Successful (all)": "Existoso (todo)",
	"Successful (non-reinvaded)": "Existoso (no reinvadido)",
	"Successful (reinvaded)": "Existoso (reinvadido)",
	"Unknown": "Desconocido",
	"Incursion": "Incursion",
	"Trial or Research only": "Prueba o Investigación",
	"Disease": "Enfermedad",
	"Hunting": "Cacería ",
	"Trapping": "Trampa",
	"Toxicant": "Intoxicante",
	"Other": "Otro",
	"Åland Islands": "Åland Islands",
	"Albania": "Albania",
	"Algeria": "Argelia",
	"American Samoa": "Samoa Americana",
	"Angola": "Angola",
	"Anguilla": "Anguila",
	"Antarctica": "Antártida",
	"Antigua and Barbuda": "Antigua y Barbuda",
	"Argentina": "Argentina",
	"Aruba": "Aruba",
	"Australia": "Australia",
	"Bahamas": "Bahamas",
	"Bahrain": "Bahrein",
	"Bangladesh": "Bangladesh",
	"Barbados": "Barbados",
	"Belgium": "Bélgica",
	"Belize": "Bélice",
	"Benin": "Benin",
	"Bermuda": "Bermuda",
	"Bosnia and Herzegovina": "Bosnia y Herzegovina",
	"Bouvet Island": "Isla Bouvet",
	"Brazil": "Brasil",
	"British Indian Ocean Territory": "Territorio Oceánico Británico Indio",
	"Brunei Darussalam": "Brunei Darussalam",
	"Bulgaria": "Bulgaria",
	"Cambodia": "Camboya",
	"Cameroon": "Camerún",
	"Canada": "Canadá",
	"Cape Verde": "Cabo Verde",
	"Cayman Islands": "Islas Caimán",
	"Chile": "Chile",
	"China": "China",
	"Christmas Island": "Islas de Navidad",
	"Cocos (Keeling) Islands": "Isla del Coco",
	"Colombia": "Colombia",
	"Comoros": "Comoras",
	"Congo": "Congo",
	"Congo, The Democratic Republic of the": "República Democrática del Congo",
	"Cook Islands": "Islas Cook",
	"Costa Rica": "Cosa Rica",
	"Côte D'Ivoire": "Côte d’Ivoire",
	"Croatia": "Croacia",
	"Cuba": "Cuba",
	"Cyprus": "Chipre",
	"Denmark": "Dinamarca",
	"Djibouti": "Djibouti",
	"Dominica": "Dominica",
	"Dominican Republic": "República Dominicana",
	"Ecuador": "Ecuador",
	"Egypt": "Egipto",
	"El Salvador": "El Salvador",
	"Equatorial Guinea": "Guinea Ecuatorial",
	"Eritrea": "Eritrea",
	"Estonia": "Estonia",
	"Falkland Islands (Malvinas)": "Islas Malvinas (Falklands)",
	"Faroe Islands": "Islas Feroe",
	"Fiji": "Fiji",
	"Finland": "Finlandia",
	"France": "Francia",
	"French Guiana": "Guayana Francesa",
	"French Polynesia": "Polinesia Francesa",
	"French Southern Territories": "Tierras Australes y Antárticas Francesas",
	"Gabon": "Gabón",
	"Gambia": "Gambia",
	"Georgia": "Georgia",
	"Germany": "Alemania",
	"Ghana": "Ghana",
	"Gibraltar": "Gibraltar",
	"Greece": "Grecia",
	"Greenland": "Groenlandia",
	"Grenada": "Granada",
	"Guadeloupe": "Guadalupe",
	"Guam": "Guam",
	"Guatemala": "Guatemala",
	"Guernsey": "Guernsey",
	"Guinea": "Guinea",
	"Guinea-Bissau": "Guinea-Bissau",
	"Guyana": "Guyana",
	"Haiti": "Haití",
	"Heard Island and Mcdonald Islands": "Islas de Heard y McDonald",
	"Honduras": "Honduras",
	"Hong Kong": "Hong Kong",
	"Iceland": "Islandia",
	"India": "India",
	"Indonesia": "Indonesia",
	"Iran, Islamic Republic of": "República Islámica de Irán",
	"Iraq": "Iraq",
	"Ireland": "Irlanda",
	"Isle of Man": "Isla de Man",
	"Israel": "Israel",
	"Italy": "Italia",
	"Jamaica": "Jamaica",
	"Japan": "Japón",
	"Jersey": "Jersey",
	"Kenya": "Kenya",
	"Kiribati": "Kiribati",
	"Korea, Democratic People'S Republic of": "República Popular Democrática de Corea",
	"Korea, Republic of": "República de Corea",
	"Kuwait": "Kuwait",
	"Latvia": "Letonia",
	"Lebanon": "Líbano",
	"Liberia": "Liberia",
	"Libyan Arab Jamahiriya": "Jamahiriya Árabe Libia",
	"Lithuania": "Lituania",
	"Macao": "Macao",
	"Madagascar": "Madagascar",
	"Malaysia": "Malasia",
	"Maldives": "Maldivas",
	"Malta": "Malta",
	"Marshall Islands": "Islas Marshall",
	"Martinique": "Martinica",
	"Mauritania": "Mauritania",
	"Mauritius": "Mauricio",
	"Mayotte": "Mayotte",
	"Mexico": "México",
	"Micronesia, Federated States of": "Estados Federados de Micronesia ",
	"Moldova, Republic of": "República de Moldova",
	"Monaco": "Mónaco",
	"Montenegro": "Montenegro",
	"Montserrat": "Montserrat",
	"Morocco": "Marruecos",
	"Mozambique": "Mozambique",
	"Myanmar": "Myanmar",
	"Namibia": "Namibia",
	"Nauru": "Nauru",
	"Netherlands": "Países Bajos",
	"Netherlands Antilles": "Antillas Neerlandesas",
	"New Caledonia": "Nueva Caledonia",
	"New Zealand": "Nueva Zelandia",
	"Nicaragua": "Nicaragua",
	"Nigeria": "Nigeria",
	"Niue": "Niue",
	"Norfolk Island": "Islas Norfolk",
	"Northern Mariana Islands": "Islas Marianas Septentrionales",
	"Norway": "Noruega",
	"Oman": "Omán",
	"Pakistan": "Pakistán",
	"Palau": "Palau",
	"Palestinian Territory, Occupied": "Territorio Palestino, Ocupado",
	"Panama": "Panamá",
	"Papua New Guinea": "Papúa Nueva Guinea",
	"Peru": "Perú",
	"Philippines": "Filipinas",
	"Pitcairn": "Pitcairn",
	"Poland": "Polonia",
	"Portugal": "Portugal",
	"Puerto Rico": "Puerto Rico",
	"Qatar": "Qatar",
	"Reunion": "Reunión",
	"Romania": "Rumania",
	"Russian Federation": "Federación de Rusia",
	"Saint Barthélemy": "Saint-Barthelémy",
	"Saint Helena": "Santa Elena",
	"Saint Kitts And Nevis": "Saint Kitts y Nevis",
	"Saint Lucia": "Santa Lucía",
	"Saint Martin": "San Martín",
	"Saint Pierre and Miquelon": " Saint Pierre y Miquelon",
	"Saint Vincent and the Grenadines": "San Vicente y las Granadinas",
	"Samoa": "Samoa",
	"Sao Tome and Principe": "Santo Tomé y Príncipe",
	"Saudi Arabia": "Arabia Saudita",
	"Senegal": "Senegal",
	"Seychelles": "Seychelles",
	"Sierra Leone": "Sierra Leona",
	"Singapore": "Singapur",
	"Slovenia": "Eslovenia",
	"Solomon Islands": "Islas Salomón",
	"Somalia": "Somalia",
	"South Africa": "Sudáfrica",
	"South Georgia and the South Sandwich Islands": "Islas Georgia y Sandwich del Sur",
	"Spain": "España",
	"Sri Lanka": "Sri Lanka",
	"Sudan": "Sudán",
	"Suriname": "Suriname",
	"Svalbard and Jan Mayen": "Islas Svalbard y Jan Mayen",
	"Sweden": "Suecia",
	"Syrian Arab Republic": "República Árabe Siria",
	"Taiwan, Province of China": "Provincia China de Taiwán",
	"Tanzania, United Republic of": "República Unida de Tanzanía ",
	"Thailand": "Tailandia",
	"Timor-Leste": "Timor-Leste",
	"Togo": "Togo",
	"Tokelau": "Tokelau",
	"Tonga": "Tonga",
	"Trinidad and Tobago": "Trinidad y Tabago",
	"Tunisia": "Túnez",
	"Turkey": "Turquía",
	"Turks and Caicos Islands": "Islas Turcas y Caicos",
	"Tuvalu": "Tuvalu",
	"Ukraine": "Ucrania",
	"United Arab Emirates": "Emiratos Árabes Unidos",
	"United Kingdom": "Reino Unido",
	"United States": "Estados Unidos",
	"United States Minor Outlying Islands": "Islas Ultramarinas Menores de Estados Unidos",
	"Uruguay": "Uruguay",
	"Vanuatu": "Vanuatu",
	"Venezuela": "Venezuela",
	"Viet Nam": "Vietnam",
	"Virgin Islands, British": "Islas Vírgenes Británicas",
	"Virgin Islands, U.S.": "Islas Vírgenes de los Estados Unidos",
	"Wallis And Futuna": "Islas Wallis y Futuna",
	"Western Sahara": "Sahara Occidental",
	"Yemen": "Yemen",
	"Cane Toad": "Cane Toad",
	"Coqui Antillano/ Lesser Antillean Whistling Frog": "Coqui Antillano",
	"Cuban Tree-Frog": "Rana platanera",
	"Eastern Narrowmouth Toad": "Eastern Narrowmouth Toad",
	"Golden-Bell Frog": "Litoria aurea",
	"Green Frog": "Rana verde",
	"Greenhouse Frog": "Rana ladrona de invernaderos",
	"Indian Bullfrog": "Rana tigre",
	"North American Bullfrog": "Rana catesbeiana",
	"Pig Frog": "Rana grylio",
	"Puerto Rican Coqui": "Coqui común",
	"Ranita X": "Ranita X",
	"Scinax Ruber": "Ranita listada",
	"Southern Leopard Frog": "Rana utricularia",
	"Squirrel Tree Frog": "Squirrel Tree Frog",
	"Unnamed Frog 1": "Rana sin nombre 1",
	"Unnamed Frog 2": "Rana sin nombre 2",
	"Unspecified Frog": "Rana sin especificar",
	"Whistling Frog": "Whistling Frog",
	"American Crow": "Cuervo americano",
	"Australasian Grebe": "Zampullín australiano",
	"Australian Magpie": "Urraca australiana",
	"Black Drongo": "Drongo real",
	"Black Francolin": "Francolín Común",
	"Brown-necked Raven": "Cuervo Desertícola",
	"Canada Goose": "Barnacla Canadiense",
	"Cattle Egret": "Garcilla Bueyera",
	"Chinese Hwamei": "Charlatán Canoro",
	"Chukor": "Perdiz Chucar",
	"Common Myna": "Miná Común",
	"Common Pheasant": "Faisán Vulgar",
	"Common Starling": "Estornino Pinto",
	"Common Waxbill": "Pico de Coral",
	"Crimson Rosella": "Perico Elegante",
	"Domestic Chicken": "Gallo/Gallina",
	"Eastern Rosella": "Perico Multicolor",
	"Eurasian Collared Dove": "Tórtola Turca",
	"Eurasian Tree Sparrow": "Gorrión Molinero",
	"European Goldfinch": "Jilguero Europeo",
	"European Greenfinch": "Verderón Común",
	"Fishers Lovebird": "Inseparable de Fischer",
	"Green Junglefowl": "Gallo de Java",
	"Grey partridge": "Francolín Gris",
	"House Crow": "Cuervo Indio",
	"House Sparrow": "Gorrión Común",
	"Island Collared Dove": "Tórtola Bicollar",
	"Japanese Bush-warbler": "Ruiseñor Bastardo Japonés",
	"Japanese White-eye": "Anteojitos Japonés",
	"Jungle Crow": "Cuervo de la Selva",
	"Jungle Myna": "Miná de la Jungla",
	"Kiskadees": "Bienteveo Común",
	"Laughing Kookaburra": "Cucaburra Común",
	"Madagascar Red Fody": "Fodi Rojo",
	"Mallard": "Anade real",
	"Monk Parakeet": "Cotorra Monje",
	"Muscovy Duck": "Pato Criollo",
	"Nankeen Kestrel": "Cernícalo Australiano",
	"Night Heron": "Martinete Coronado",
	"Northern Cardinal": "Cardenal Norteño",
	"Orange-cheeked Waxbill": "Estrilda Carinaranja",
	"Red Junglefowl": "Gallo Bankiva",
	"Red-Billed Leiothrix": "Leiotrix Piquirrojo",
	"Red-masked Parakeet": "Aratinga de Guayaquil",
	"Red-vented Bulbul": "Bulbul Cafre",
	"Red-whiskered Bulbul": "Bulbul Orfeo",
	"Ringed Turtle-dove": "Tórtola Rosigrís",
	"Rock Dove": "Paloma Bravía",
	"Rose-ringed Parakeet": "Cotorra de Kramer",
	"Ruddy Duck": "Pato Zambullidor Grande",
	"Shiny Cowbird": "Tordo Renegrido",
	"Silvereye": "Ojiblanco de Lomo Gris",
	"Smooth-billed Ani": "Garrapatero Aní",
	"Southern Boobook": "Nínox Maorí",
	"Swamp Harrier": "Aguilucho Lagunero del Pacífico",
	"Tiuque / Chimango Caracara": "Tiuque/Caracara",
	"Unspecified Birds": "Ave no especificada",
	"Unspecified Gull": "Gaviota no especificada",
	"Unspecified Peacock": "Pavo no especificado",
	"Weka": "Rascón Weka",
	"White-rumped Shama": "Shama Culiblanco",
	"White-Winged Dove": "Zenaida Aliblanca",
	"Wild Turkey": "Guajolote Gallipavo",
	"Yellow-crowned Amazon": "Amazona Real",
	"Australian Masked-owl": "Lechuza de Campanario Enmascarada",
	"Barn Owl": "Lechuza Común",
	"Great Horned Owl": "Búho Americano",
	"Harris's Hawk": "Busardo Mixto",
	"African Civet": "Civeta africana",
	"Caracal": "Caracal",
	"Domestic Cat": "Gato Doméstico",
	"Malay Civet": "Civet Malaya",
	"Wildcat": "Gato Montés",
	"Arctic Fox": "Zorro Ártico",
	"Bat-Eared Fox": "Otoción",
	"Cape Fox": "Zorro del Cabo",
	"Dingo": "Dingo",
	"Domestic Dog": "Perro Doméstico",
	"Grey Wolf": "Lobo",
	"Red Fox": "Zorro Común",
	"Silver-grey Fox": "Zorro Gris",
	"Unspecified Fox": "Zorro no especificado",
	"African Sharptooth Catfish": "Carpa",
	"Asian Snakehead": "Ofiocéfalo",
	"Bighead Carp": "Carpa cabezona",
	"Blue Tilapia": "Tilapia azul",
	"Brown Trout": "Trucha Común",
	"Carp": "Carpa común",
	"Congo Tilapia": "Tilapia  ",
	"Eastern mosquitofish": "Gambusia",
	"Goldfish": "Carpa Dorada",
	"Grass Carp": "Carpa Hervíbora",
	"Green Swordtail": "Xipho",
	"Guppy": "Pez Millón",
	"Largemouth Bass": "Lubina Negra",
	"Mozambique Tilapia": "Tilapia de Mozambique",
	"Nile Perch": "Perca del Nilo",
	"Perche africaine": "Perca Africana",
	"Rainbow Trout": "Trucha arcoiris",
	"Red Lionfish": "Pez León Colorado",
	"Redbelly Tilapia": "Redbelly Tilapia",
	"Salmon Trout": "Trucha arcoiris",
	"Silver Carp": "Carpa plateada",
	"Silverside": "Pejerrey",
	"Snakehead Fish": "Pez Cabeza de Serpiente",
	"Snakehead Murrel": "Cabeza de serpiente cabrío",
	"Unspecified Catfish": "Claria",
	"Unspecified Cyprinid Fish": "Carpa",
	"Unspecified Fish": "Pez no especificado",
	"Unspecified Snakehead Fish": "Pez Cabeza de Serpiente no especificado",
	"Unspecified Tilapia Fish": "Tilapia no especificada",
	"Argentine Ant": "Hormiga Argentina",
	"Big-headed Ant": "Hormiga Leona",
	"Cactus Moth": "Palomilla del Nopal",
	"Common Greenbottle Fly": "Mosca corónida verde",
	"Common Wasp": "Avispa Común",
	"Ectoparasitic botfly": "Mosca Ectoparásita",
	"Fire Ant": "Hormiga de Fuego",
	"Freshwater Shrimp": "Camarón Gigante de Aguadulce",
	"Garlic Snail": "Culebra Garlic",
	"Honey Bee": "Abeja Europea",
	"Louisiana Crayfish": "Cangrejo Rojo Americano",
	"Parasitic Nematode": "Nemátodo Parásito",
	"Pharaoh Ant": "Hormiga Faraón",
	"Small Fire Ant": "Candelilla",
	"Two-spotted Leafhopper": "Chicharrita",
	"Unspecified Ants": "Hormiga no especificada",
	"Unspecified Cockroach": "Cucaracha no especificada",
	"Unspecified Fire Ants": "Hormiga de Fuego no especificada",
	"Unspecified Insects": "Insecto no especificado",
	"Unspecified Wasps": "Avispa no especificada",
	"Western Yellowjacket": "Avispa Chaqueta Amarilla",
	"Yellow Crazy Ant": "Hormiga loca",
	"Yellow Jacket Wasp": "Avispa Chaqueta Amarilla",
	"Yellow Paper Wasp": "Yellow Paper Wasp",
	"Agile Wallaby": "Wallaby Ágil",
	"Algerian Hedgehog": "Erizo Moruno",
	"American Beaver": "Castor Americano",
	"American Red Squirrel": "Ardilla Roja Americana",
	"Amur Hedgehog": "Erizo de Manchuria",
	"Arctic Ground Squirrel": "Ardilla de Tierra del Ártico",
	"Asian Elephant": "Elefante Asiático",
	"Asian Palm Civet": "Civeta de las palmeras común",
	"Bahama Hutia": "Hutia de Bahamas",
	"Barbary Ground Squirrel": "Ardilla moruna",
	"Black-striped Wallaby": "Wallaby Rayas Negras",
	"Brown's Pademelon": "Pademelón de Brown",
	"Cape Serotine Bat": "Neoromicia capensis",
	"Common Brushtail Possum": "Zarigüeya Australiana",
	"Common Genet": "Jineta",
	"Common Marmoset": "Tití Común",
	"Common Opossum": "Zarigüeya Común",
	"Common Spotted Cuscus": "Cucús Moteado",
	"Common Tenrec": "Tenrec Común",
	"Eastern Chipmunk": "Ardilla Listada",
	"Eastern Quoll": "Quol Oriental",
	"Egyptian Fruit Bat": "Murciélago Egipcio",
	"Elegant Fat-Tailed Mouse Opossum": "Yaca",
	"Eurasian Red Squirrel": "Ardilla Roja Común ",
	"Gray Squirrel": "Ardilla de las Carolinas",
	"Hoary Marmot": "Marmota",
	"Japanese Macaque": "Macaco Japonés",
	"Javanese Porcupine": "Puerco Espín de Java",
	"Large Opossum": "Zarigüeya Gris",
	"Nine-banded Armadillo": "Armadillo de Nueve Bandas",
	"Northern Common Cuscus": "Cucús Gris",
	"Pallas Squirrel": "Ardilla de Pallas",
	"Parma Wallaby": "Walaby Parma",
	"Raccoon": "Mapache boreal",
	"Red-necked Wallaby": "Walaby de Cuello Rojo",
	"Rock Hyrax": "Damán del Cabo",
	"Siberian Chipmunk": "Ardilla de Siberia",
	"Small Indian Civet": "Civeta Enana",
	"South American Coati": "Coatí de Cola Anillada",
	"Southern Common Cuscus": "Cuscún Común de Oriente",
	"Striped Palm Squirrel": "Ardilla de Palma",
	"Swamp Wallaby": "Walabi de Pantano",
	"Tammar Wallaby": "Walabi de Astralia",
	"Tasmanian Bettong": "Canguro Rata de Tasmania",
	"Unspecified Mammals": "Mamífero no especificado",
	"Unspecified possum": "Zarigüeya no especificada",
	"Unspecified Squirrel": "Ardilla no especificada",
	"Unspecified Tenrec": "Tenrec no especificado",
	"Virginia Opossum": "Zarigüeya de Virginia",
	"West European Hedgehog": "Erizo de Tierra Común ",
	"White-tailed Antelope Squirrel": "Ardilla Antílope de Cola Blanca",
	"Zanj Sun Squirrel": "Ardilla de Sol",
	"American Mink": "Visón Americano",
	"Beech Marten": "Garduña",
	"Cape Grey Mongoose": "Mangosta Gris del Cabo",
	"Egyptian Mongoose (Large Grey Mongoose)": "Mangosta Común",
	"European Pine Marten": "Marta",
	"European Polecat": "Hurón Europeo",
	"Ferret": "Hurón Doméstico",
	"Indian Grey Mongoose": "Magosta Indú",
	"Japanese Marten": "Marta Japonesa",
	"Japanese Weasel": "Comadreja Japonesa",
	"Least Weasel": "Comadreja común ",
	"Siberian Weasel": "Comadreja Siberiana",
	"Small Asian (Javan) Mongoose": "Mangosta Pequeña Asiática (Java)",
	"Small Indian Mongoose": "Mangosta Pequeña Asiática",
	"Stoat / Ermine": "Armiño",
	"Unspecified Mongoose": "Magosta no especificada",
	"Unspecified Weasel": "Comadreja no especificada",
	"Water Mongoose (Marsh Mongoose)": "Moangosta Acuática",
	"Yellow Mongoose": "Mangosta de Cola Gruesa",
	"NONE": "Ninguno",
	"Crab-eating Macaque": "Macaco  Cangrejero",
	"Green Monkey / Grivet": "Cercopiteco Verde",
	"Grivet Monkey": "Grivet Monkey",
	"Mona Monkey": "Cercopiteco Mona",
	"Rhesus Macaque": "Macaco Rhesus",
	"Southern Pig-tailed Macaque": "Macaco Cola de Chancho",
	"Taiwan Macaque": "Macaco de Formosa",
	"Unspecified Macaque": "Macaco no especificado",
	"Black-tailed Jack Rabbit": "Liebre de California",
	"Brush-tailed Rock Wallaby": "Walabi cola de cepillo",
	"Cape Hare": "Liebre del Cabo",
	"Cottontail": "Conejo de Florida",
	"European Hare": "Liebre Europea",
	"European Rabbit": "Conejo Europeo",
	"Indian Hare": "Liebre India",
	"Snowshoe Hare": "Liebre Americana",
	"Unspecified Rabbit": "Conejo/Liebre sin especificar",
	"Afro-American House Gecko": "Tuqueque",
	"Barbados Anole": "Barbados Anole",
	"Bronze Anole": "Bronze Anole",
	"Brown Anole": "Anolis Sagrei",
	"Common Agama": "Agama Común",
	"Common House Gecko": "Gecko Casero",
	"Common Iguana": "Iguana Común",
	"Cuban Brown Anole": "Cuban Brown Anole",
	"Cuban Green Anole": "Cuban Green Anole",
	"Curious Skink": "Curious Skink",
	"Diamondback Terrapin": "Tortuga Espalda de Diamante",
	"Eastern Glass Lizard": "Eastern Glass Lizard",
	"Four-fingered Skinks": "Carlia ailanpalai",
	"Giant Black and White Tegu": "Lagarto Overo",
	"Gould's Monitor Lizard": "Varano de Gould",
	"Green Anole ": "Green Anole ",
	"Green Tree Skink": "Green Tree Skink",
	"Grenada Tree Anole": "Grenada Tree Anole",
	"Haitian Big-scaled Sphaero": "Haitian Big-scaled Sphaero",
	"Heath Monitor Lizard": "Heath Monitor Lizard",
	"Inagua Slider": "Inagua Slider",
	"Indian Monitor Lizard": "Verano de Bengala",
	"Indo-Pacific House Gekko": "Gecko del Indo-Pacífico",
	"Italian Wall Lizard": "Lagartija Italiana",
	"Jamaican Anole": "Lagartija Jamaicana",
	"Knight Anole": "Anolis Ecuestre",
	"Land Iguana": "Iguana Terrestre de Galápagos",
	"Madagascar Giant Day Gecko": "Gecko Diurno de Madagascar",
	"Mangrove Monitor Lizard": "Verano de Manglar",
	"Mourning Gecko": "Gecko Enlutado",
	"Mutilating Gecko": "Gecko Plano",
	"Oceanic Gecko": "Gecko Oceánico",
	"Puerto Rican Anole": "Lagartijo boricua",
	"Rainbow Skink": "Lampropholis delicata",
	"Red-Eared Slider": "Tortuga de orejas rojas",
	"Red-footed Tortoise": "Tortuga Terrestre de Patas Rojas",
	"Reissi Gecko": "Gecko Reissi",
	"Saint Vincent's Bush Anole": "Anolis de Trinidad",
	"Savannah Monitor Lizard": "Verano de Sabana",
	"Shingleback": "Escinco Rugoso",
	"Spectacled Caiman": "Caimán de Anteojos",
	"Sugar glider": "Petauro del Azúcar",
	"Tokay Gecko": "Gecko Tokay",
	"Tuberculosus Gecko": "Salamanqueja Vientre Amarillo",
	"Underwood's Spectacled Tegu": "Underwood's Spectacled Tegu",
	"Unspecified Slider": "Tortuga no especificada",
	"Warwick Lizard": "Anolis leachii",
	"Watts Anole": "Anolis wattsi",
	"Yellow-bellied Slider": "Tortuga Pintada",
	"Barbour's Tropical Racer": "Mastigodryas bruesi",
	"Boa Constrictor": "Boa Constrictora",
	"Brahminy Blind Snake": "Culebrilla de las Macetas",
	"Brown Snake": "Culebra Parda de Kay",
	"Brown Tree Snake": "Culebra Arbórea Café",
	"Burmese Python": "Pitón de Birmania",
	"Common Garter Snake": "Culebra Rayada",
	"Eastern Box Snake": "Tortuga de Caja Común",
	"Eastern Rat Snake": "Serpiente de Rata Negra",
	"Red Cornsnake": "Serpiente del Maíz",
	"Ring-necked Snake": "Culebra de Collar Amarillo",
	"Unspecified Snake": "Culebra no especificada",
	"Algerian Mouse": "Ratón Moruno",
	"Arctic Lemming": "Rata de Campo",
	"Asian House Rat": "Asian House Rat",
	"Asian House Shrew": "Musaraña Casera",
	"Black Rat": "Rata Negra",
	"Brazilian Agouti": "Agutí Brasileño",
	"Brown / Norway Rat": "Rata Noruega",
	"Brown Country Rat": "Brown Country Rat",
	"Cactus Mouse": "Rata de Cactus",
	"Cairo Spiny Mouse": "Ratón Espinoso Egipcio",
	"Capybara": "Carpincho",
	"Central American Agouti": "Agutí Centroamericano",
	"Domesticated Guinea Pig": "Conejillo de Indias",
	"Gambian Rat": "Rata de Gambia",
	"Garden Dormouse": "Lirón Careto",
	"Greater Bandicoot Rat": "Greater Bandicoot Rat",
	"Greater White-toothed Shrew": "Musaraña Gris",
	"Himalayan Rat": "Rata del Himalaya",
	"House Mouse": "Ratón Casero",
	"Javanese Shrew": "Musaraña de Java",
	"Lesser Dwarf Shrew": "Lesser Dwarf Shrew",
	"Lowland Paca": "Paca Común",
	"Madagascan Pygmy Shrew": "Musaraña Pigmea de Madagascar",
	"Mexican Agouti": "Agutí Negro",
	"North American Deermouse": "Ratón Ciervo",
	"Northern Baja Deermouse": "Ratón de Baja California",
	"Nutria": "Coipo",
	"Olive Grass Mouse": "Ratón Olivaceo",
	"Polynesian Rat": "Rata de la Polinesia",
	"Pygmy Mouse": "Ratón Pigmeo Africano",
	"Red-tailed Squirrel": "Ardilla de Cola Roja",
	"Ricefield Rat": "Ratón del Arrozal",
	"Santa Lucia Agouti": "Agutí de Santa Lucía",
	"Spiny Rat": "Rata Espinosa",
	"Unspecified Agouti": "Agutí no especificado",
	"Unspecified Mice": "Ratón no especificado",
	"Unspecified porcupine": "Puercoespín no especificado",
	"Unspecified Rats": "Rata no especificada",
	"Unspecified Rodent": "Roedor no especificado",
	"White-toothed Pygmy Shrew": "Musarañita",
	"Woodmouse": "Ratón de Campo",
	"Alpine Chamois": "Rebeco",
	"Babirusa": "Babirusa",
	"Banteng": "Banteng",
	"Barbary Sheep": "Arruí",
	"Barking Deer": "Muntíaco de la India",
	"Big-horn Sheep": "Musmón",
	"Blackbuck": "Antílope Indio",
	"Bontebok": "Bontebok",
	"Buffalo": "Bisonte Americano",
	"Bush Pig": "Potamoquero de Río",
	"Cape Grysbok": "Grysbok del Cabo",
	"Chital (Barking Deer)": "Ciervo Moteado",
	"Common Eland": "Antílope Eland Común",
	"Domestic Cow": "Vaca Doméstica",
	"Domestic Pig": "Cerdo",
	"Domestic Sheep": "Oveja Doméstica",
	"Donkey": "Burro",
	"Elk": "Ciervo Canadiense",
	"Eurasian Elk": "Alce",
	"Fallow Deer": "Gamo Común",
	"Giant Eland": "Eland Gigante",
	"Goat": "Cabra",
	"Himalayan Tahr": "Tar del Himalaya",
	"Hog Deer": "Ciervo Porcino",
	"Horse": "Caballo",
	"Javan Rusa": "Ciervo de Timor",
	"Llama": "Llama",
	"Mouflon": "Muflón",
	"Mountain Goat": "Cabra Blanca ",
	"Mountain Sheep": "Argalí",
	"Mule Deer": "Ciervo Mulo",
	"Nilgai": "Nilgó",
	"One-humped Camel": "Camello Arábigo",
	"Peccary": "Pecarí de Collar",
	"Philippine Sambar Deer": "Sambar Filipino",
	"Red Deer": "Ciervo Rojo",
	"Reindeer": "Reno",
	"Rusa Deer": "Sambar de Timor",
	"Sambar": "Sambar",
	"Sika Deer": "Ciervo Sica",
	"Springbok": "Gacela Saltarina",
	"Steenbuck": "Raficero Común",
	"Sulawesi Warty Pig": "Jabalí Berrugoso",
	"Tatabro": "Tatabro",
	"Unspecified Deer": "Ciervo no especificado",
	"Unspecified Ungulate": "Ungulado no especificado",
	"Water Buffalo": "Búfalo",
	"White-tailed Deer": "Ciervo de Cola Blanca",
	"Wild Boar/Pig": "Jabalí/Cerdo",
	"Wild Goat": "Cabra Salvaje",
	"Zebu": "Cebú",
	"References": "Referencias",
	"Data Quality": "Calidad de la Información",
	"Publication": "Publicaciones",
	"Grey literature": "Literatura informal",
	"Online Database": "Base de datos en línea",
	"Popular Press": "Medios de comunicación masivos",
	"Other": "Otros",
	"Island Eradication Type": "Tipo de Erradicación de Isla",
	"Whole Island": " Isla Completa",
	"Restricted range": "Rango Restringido",
	"Fence area": "Área Cercada",
	"Incursion": "Incursión"
}

var config_byId_es = {
	"link_about": "Sobre",
	"link_news": "Noticias",
	"link_disclaimer": "Descargo de Responsabilidad",
	"link_terms": "Condiciones de Uso",
	"link_help": "Cómo Ayudar",
	"link_partners": "Socios",
	"link_contact": "Contacto",
	"link_more": "Más Info",
	"app_language_text": "Lengua:",
	"language_english_text": "Inglés",
	"language_spanish_text": "Español",
	"splash_language_text": "Lengua:",
	"splash_language_english": "Inglés",
	"splash_language_spanish": "Español",
	"cisr": "construido por el <a target=\"_blank\" href=\"http://spatial.cisr.ucsc.edu\">centro para investigación espacial integrada (cisr)</a> @ <a target=\"_blank\" href=\"http://www.ucsc.edu\">ucsc</a>",
	"graphicText": "Grafico:",
	"rectangle": "... por Rectangulo",
	"polygon":  "... por Poligono",
	"basemap_basic": "Básico",
	"basemap_satellite": "Satélite",
	"basemap_topographic": "Topográfico",
	"printOptionsTextNode": "Exportar el Mapa",
	"csvOptionsTextNode": "Exportar a CSV",
	"regionSelect_label": "Región:",
	"countrySelect_label": "Pais:",
	"islandSelect_label": "Isla:",
	"invasiveTypeSelect_label": "Tipo:",
	"invasiveScientificSelect_label": "Nombre Científico:",
	"invasiveCommonSelect_label": "Nombre Común:",
	"inv_sci_label": "Nombre Científico",
	"inv_com_label": "Nombre Común",	
	"eradicationStatusSelect_label": "Estado:",
	"eradicationMethodSelect_label": "Método Principal:",
	"csvTermsCheck_label": "Estoy de acuerdo con la condiciones que se indican en los términos y Condiciones de Uso sobre.",
	"printTermsCheck_label": "Estoy de acuerdo con la condiciones que se indican en los términos y Condiciones de Uso sobre.",	
	"queryDefinition": "Filtro:",
	"r_islands_text": "Número de islas",
	"invasives_sum_text": "erradicaciones",
	"r_invasives_text": "Número de especies",
	"r_type_animal": "Tipo (Animal)",
	"r_status_eradication": "Estado (Erradicación)",
	"islandTitle": "Ninguna Isla Seleccionada",
	"table_header_text": "Tabla",
	"noThumbnails": "No se encontraron imágenes 'thumbnail'...",
	"aboutContent": "<span class=\"aboutHeader\">Qué es la Base de Datos de Erradicaciones de Especies Invasoras?</span><br/>Las Islas son el epicentro de la actual crisis global de extinciones, siendo los vertebrados invasores la principal causa de extinciones en islas. La remoción de vertebrados invasores es una herramienta arraigada para proteger y restaurar los ecosistemas insulares y prevenir extinciones.<p>La Base de Datos de Erradicaciones de Especies Invasoras en Islas compila información histórica y actual sobre las erradicaciones de vertebrados invasores en islas. Los datos de cada proyecto incluyen información sobre la isla, métodos usados en la erradicación e información de contacto de las personas expertas en la erradicación.</p><p>Nuestra esperanza es que la base de datos facilitará:</p><ul type=\"circle\"><li>El intercambio de información: Mejorando la transferencia de conocimiento entre practicantes de métodos de erradicación. Proporcionando contactos sobre cada proyecto de erradicación para facilitar la comunicación entre erradicadores experimentados y aquellos en busca de asistencia. </li><li>Evaluación de técnicas: El seguimiento de los intentos de erradicación para analizar donde, como, y quien esta llevando a cabo estos esfuerzos; cuales técnicas son exitosas y resaltando las especies invasoras para las cuales las técnicas aún son deficientes.</li><li>Generación de fondos: Esta base de datos es una herramienta valiosa para recaudar fondos al permitirle a los practicantes conceptualizar  propuestas de proyectos de erradicacion en islas con base en un marco global de erradicaciones e información histórica sobre intentos de erradicación. </li></ul>",
	"chartNodeText":"<b>Figura 1</b>. Número acumulativo de erradicaciones exitosas por año desde 1950.",
	"howToCite": "<span class=\"aboutHeader\">Cómo citar?</span> <br/>DIISE, 2015. The Database of Island Invasive Species Eradications, developed by Island Conservation, Coastal Conservation Action Laboratory UCSC, IUCN SSC Invasive Species Specialist Group, University of Auckland and Landcare Research New Zealand. http://diise.islandconservation.org.<br/>",
	"aboutReferenceHeader": "Bibliografía",
	"aboutFunding": "La Database of Island Invasive Vertebrate Eradications fue creada con el apoyo financiero del David and Lucille Packard Foundation, el National Fish and Wildlife Foundation y el Fondo para el Medio Ambiente Mundial.",
	"errorContent": '"Island Conservation" se esfuerza por mantener datos precisos y actualizados en todo momento. Sin embargo, de identificarse errores u omisiones, el usuario debe notificar a "Island Conservation" para que estos puedan ser corregidos en la base de datos. Los usuarios pueden contactar a "Island Conservation" <a href=\"mailto:science@islandconservation.org\">science@islandconservation.org</a> utilizando los detalles al final de estos términos de uso. Cualquier correspondencia por favor enviarla con el titulo: "Base de datos de islas y erradicaciones de especies invasoras".',
	"disclaimerContent": "\"Island Conservation\" no establece garantías o representaciones, de forma expresa o implícita con respecto a la presición, veracidad o confiabilidad del material que aparece en la base de datos. El material y las designaciones geográficas en esta base de datos no reflejan la opinión de \"Island Conservation\" con respecto al estado legal de ningún país, territorio, o área, ni con respecto a la delimitación de su territorio o fronteras. Ni \"Island Conservation\", ni sus entidades afiliadas, o relacionadas,  ni quienes proporcionan el contenido de esta página se hacen responsables ante ninguna persona, firma o corporación por pérdida, daño, perjuicio, demanda o responsabilidad legal  como resultado de  información contenida en la base de datos. \"Island Conservation\" puede actualizar o realizar cambios a los datos proporcionados en cualquier momento y sin noticia previa; sin embargo, \"Island Conservation\" no se compromete a actualizar la información contenida en esta página de internet y sus bases de datos.",
	"termsOfUseContent": '<ol><li>Los datos son suministrados solo para propósitos de conservación, análisis científico o investigación.</li><li>El usuario de los datos otorgará completo y apropiado reconocimiento y hará la mención pertinente en cualquier material o publicaciones derivadas en parte o por entero de los datos aquí suministrados; se proporcionarán detalles relevantes sobre la forma apropiada de citar cada conjunto de datos. Para cualquier publicación que haga uso sustancial de los datos, "Island Conservation" da la bienvenida a la oportunidad de una co-autoría, colaboración, o comentario previo a la publicación. Expresiones de interés deben ser enviadas <a href="mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE">science@islandconservation.org</a>.</li><li>La reproducción de los datos o productos derivados de los mismos, de forma completa o parcial,  para propósitos comerciales, está prohibida sin permiso previo y/o por escrito de "Island Conservation". Para estas condiciones de uso los fines "propósitos comerciales" significa a) cualquier uso por, o en beneficio de, o para informar o asistir las actividades de a) una entidad comercial (una entidad que opera "con fines de lucro") o b) uso por parte de una entidad sin fines de lucro con fines de generar recursos monetarios. Si usted requiere permiso por favor contacte a "Island Conservation" vía correo electrónico a <a href="mailto:science@islandconservation.org?Subject=Commercial%20use%20of%20DIISE">science@islandconservation.org</a> o por escrito al Departamente de Ciencia  a la dirección que se encuentra en la parte inferior.</li><li>El usuario no publicará los datos en su formato original, ya sea completa o parcialmente, en una página de internet, sitio FTP, CD, barra de memoria o cualquier otro medio. El usuario debe proveer un vínculo a la ubicación original de los datos en la página de internet del "Grupo Especialista en Especies Invasoras" de la UICN cuando esto sea apropiado.</li><li>El uso de estos datos no constituye el endoso de "Island Conservation" a ningún producto derivado, reporte o análisis. El logo de "Island Conservation" no debe utilizarse en ningún producto derivado, reporte o análisis, o en materiales de apoyo sin permiso.</li><li>"Island Conservation" se reserva el derecho de comentar sobre la presición en la representación de los datos en cualquier material producido por el usuario </li><li>"Island Conservation" se esfuerza por mantener datos precisos y actualizados en todo momento, pero no se hace responsable por las consecuencias producto de errores u omisiones en los datos, mal uso de los datos por cualquier organización o individuo, o por daños a sistemas de computadores en los cuales se hallan descargado los datos (favor leer el Descargo de Responsabilidad).</li><li>Toda copia electrónica o impresa de productos publicados utilizando los datos provistos por "Island Conservation" debe ser enviada, libre de cargo, a los autores de los datos vía correo a: Island Conservation, 2161 Delaware Ave, Suite A, Santa Cruz CA USA 95060 o vía correo electrónico a: <a href="mailto:science@islandconservation.org?Subject=Publication(s)%20using%20DIISE">science@islandconservation.org</a>.</li></ol>',
	"newsContent": "<b>Version 2015.1</b>: Importantes actualizaciones de datos fueron llevadas a cabo.",
	"partners_text": "Las personas, organizaciones y agencias que han ayudado a desarrollar la Base de Datos de Erradicaciones de Especies Invasoras en Islas",
	"userInfoTermsTitle": "Por Favor Registre Sus Datos", 
	"purposeText": "El uso previsto de los datos"
}

var config_byDijitId_es = {
	"searchContentDiv": "Búsqueda",
	"resultsContentDiv": "Resúltado",
	"islandContentDiv": "Detalles de la Isla",
	"geography": "... ubicación geográfica",
	"invasive": "... por especies invasoras",
	"eradication": "... por detalle de erradicación",
	"searchButton": "Correr búsqueda", 
	"clearButton": "Limpiar búsqueda",
	"printButton": "Exportar",
	"csvButton": "Exportar",
	"infoDetails": "Isla",
	"infoInvasive": "Erradicación(es)",
	"eradicationDetails": "Los detalles del registro de erradicación",
	"about": "Sobre la Base de Datos de Erradicaciones de Especies Invasoras",
	"news": "Noticias",
	"disclaimer": "Descargo de Responsabilidad",
	"termsOfUse": "Condiciones de uso",
	"errors": "Cómo ayudar",
	"partners": "Socios",	
	"Letter": "Carta",
	"csvContinueButton": "Continuar",
	"printContinueButton": "Continuar",
	"splash_language_spanish_tooltip": "Español",
	"splash_language_english_tooltip": "Inglés",
	"searchTool_tooltip": "Pulse para abrir/cerrar la ventana de búsqueda personalizada.",
	"resultsTool_tooltip": "Pulse para abrir/cerrar la ventana de resultados.",
	"islandsTool_tooltip": "Pulse para abrir/cerrar la ventana de detalles de isla.",
	"csvTool_tooltip": "Pulse para exportar o bajar el archivo .csv de la tabla de resultados.",
	"printTool_tooltip": "Pulse para exportar y bajar el archivo map de alta resolución.",
	"basemap_tooltip": "Pulse para cambiar el mapa base.",
	"overview_tooltip": "Pulse para abrir/cerrar la ventana de visión general del mapa.",
	"zoomfull_tooltip": "Pulse para ampliar el mapa a máxima escala.",
	"zoomin_tooltip": "Pulse para ampliar el mapa usando una extensión personalizada.", 
	"splitter_tooltip": "Pulse y arrastre para aumentar o disminuir la tabla visible.",
	"close_tooltip": "Pulse para mostrar u ocultar la tabla.",
	"search_tooltip": "Construir una búsqueda. Pulse y arrastre para mover el cuadro de diálogo para una nueva posición.",
	"results_tooltip": "Resúltados de su búsqueda. Pulse y arrastre para mover el cuadro de diálogo para una nueva posición.",
	"island_tooltip": "Información detallada de una isla específica. Pulse y arrastre para mover el cuadro de diálogo para una nueva posición.",
	"r_breeding_tooltip": "Mayús + pulse para definiciones completas de Estado Crianza.",
	"experts_tooltip": "Pulse para obtener una lista de expertos que contribuyen y el equipo de recolección de datos TIB.",
	"donate_tooltip": "Pulse para donar hacia el desarrollo DIISE a través del sitio Island Conservation Paypal.",
	"island_invasives_tooltip": "Todas las especies invasoras en una isla.",
	"userName": "Nombre y Apellido",
	"email": "Correo Electrónico",
	"org": "Organización",
	"country": "País"	
}
